### ISSUE TITLE
Special Character missing

### ISSUE THREAD

**Issue by Nosferius** [kegesch/SpecialChars#10]
Dear Jonas,

Firstly thanks for your contribution so far, I really like your brackets extension however whilst doing some work for a Swedish site I noticed the å (&aring)\* and Å (&Aring)\* are missing, might be more chars but these I regularly come across (in Swedish text this sign is very common). 

Could you please add these to your script?

Thanks a lot,

Stefan de Jong
- had to ommit the ; behind the html code for the signs as otherwise they are parsed to plain text

**Comment by kegesch** [comment]
Hello, 

thank you for helping me out. I added the chars. 

sincerely
Jonas

**Comment by Nosferius** [comment]
No problem, it helps me in the future to help you now :)

Got another few for you that I found whilst working on a Danish site. (again I left out the ; so that the code at least shows)
æ --> &aelig
Ø --> &Oslash
ø --> &oslash

I'll give a heads up if i find more.

Thanks again for your work and for the quick update

Kind regards.

Stefan

**Comment by kegesch** [comment]
added them too ;) 
yes just let me know, if you find others, because in my language (German) those chars don't exist. 

Jonas

**Comment by Nosferius** [comment]
Sure thing, I'm Dutch so I don't have many of them too but I work with many countries at the moment :)

**Comment by Nosferius** [comment]
Got another special character to add ... (again I left out the ; at the end of the code)

€ = &euro
• = &bull

**Comment by Nosferius** [comment]
Hi,

Got another few:
€ = &euro;
• = &bull;
- = &ndash;

" = &quot;

“ = &ldquo;

” = &rdquo;

‘ = &lsquo;

’ = &rsquo;

Thanks again :)

Have a good week,

Stefan

On Thu, Oct 2, 2014 at 12:57 PM, Jonas Geschke notifications@github.com
wrote:

> added them too ;)
> yes just let me know, if you find others, because in my language (German)
> those chars don't exist.
> 
> Jonas
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Y0nnyy/SpecialChars/issues/10#issuecomment-57612196.

## 

[ius vigulantis scriptum est, non dormentibus]

**Comment by kegesch** [comment]
Hey, 

I added • and €. I think if i add the others there would be a really huge problem in programming, if you know what I mean.

**Comment by Nosferius** [comment]
Hi,

Found another addition for you :)

 ò - &ograve;

 Ò - &Ograve;

Thanks :)

as for the other things yeah I understand, makes making comments hard :P
didn't think about that hehe

On Tue, Oct 28, 2014 at 8:43 PM, Jonas Geschke notifications@github.com
wrote:

> Hey,
> 
> I added • and €. I think if i add the others there would be a really huge
> problem in programming, if you know what I mean.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Y0nnyy/SpecialChars/issues/10#issuecomment-60818619.

## 

[ius vigulantis scriptum est, non dormentibus]

**Comment by joaoghummel** [comment]
Hi there,
Its missing ú and Ú. I just added myself but it would be cool to update.
Thanks.

**Comment by kegesch** [comment]
added them
