### ISSUE TITLE
Ctrl-Alt-H doesn't seem to work

### ISSUE THREAD

**Issue by carlwjacobs** [kegesch/SpecialChars#11]
Hi, Great add-on! I love using it. Just quick question: the Ctrl-Alt-H option for larger text doesn't seem to work. Any thoughts on this?

Keep up the invaluable work!

**Comment by kegesch** [comment]
Hi, thank you ;) 
Yes is recognized this earlier and don't know why. I tried some things, but it didn't work. Do you have any suggestions?

Jonas

**Comment by anephew** [comment]
@Y0nnyy 

**Ctrl+Alt+H** - **core shortcut for "Show Sidebar"** (top VIEW menu). 

Also, if you are developing extensions then look dev tools console, error of your extension here:

<code>Cannot assign Ctrl-Shift-R to specialchars.scselect. It is already assigned to file.reloadLivePreview</code>

**Ctrl-Shift-R** - **core shortcut for "reload Live Preview"**.  It is bad practice to override the standard keyboard shortcuts that users use. You must use other shortcut keys for your extension.

**Comment by kegesch** [comment]
Thank you, fixed it. Now It is Ctrl-Shift-Q.
