### ISSUE TITLE
Shortcut error

### ISSUE THREAD

**Issue by abdelouahabb** [kegesch/SpecialChars#12]
Hi,
there is  a Brackets shortcuts that collides with a shortcut `Ctrl-Shift-R`
![sans titre](https://cloud.githubusercontent.com/assets/2527234/4850362/2f399110-6069-11e4-9df3-677ed26aa2da.jpg)

**Comment by kegesch** [comment]
Thank you, fixed it. Now It is Ctrl-Shift-Q.

**Comment by abdelouahabb** [comment]
thank you :)
