### ISSUE TITLE
How to not-replace special characters?

### ISSUE THREAD

**Issue by BrainCrumbz** [kegesch/SpecialChars#14]
Thanks for this extension.
I'm writing in the middle of a comment inside a JS file. When I type a special character, I would expect that it stays untouched (as I'm not in HTML). Instead conversion happens anyway.

Is there a way I can prevent that from happening? 
Thanks

**Comment by kegesch** [comment]
Hi, 
I just added a new function. You can now uncheck the command (SpecialChars) in the Edit-Menu. 
Update the extension ;)
Y0nnyy

**Comment by BrainCrumbz** [comment]
Thanks! I'll give it a try after next update
