### ISSUE TITLE
Enchacement

### ISSUE THREAD

**Issue by joaoghummel** [kegesch/SpecialChars#15]
Hi,

Woult it be to hard to make this based in a selection instead of words?

Sincerely,
João G Hümmel

**Comment by kegesch** [comment]
Hi, 

you mean that there should be a selectionfield, where you can choose one character?

Y0nnyy

**Comment by joaoghummel** [comment]
Hi,

No, I mean select an entire paragraph, and then, use some shortcut to change any special char in it.

João G Hümmel

--- Mensagem Original ---

De: "Jonas Geschke" notifications@github.com
Enviado: 25 de novembro de 2014 18:40
Para: "Y0nnyy/SpecialChars" SpecialChars@noreply.github.com
Cc: "JoaoGHummel" joaoghummel@outlook.com
Assunto: Re: [SpecialChars] Enchacement (#15)

Hi,

you mean that there should be a selectionfield, where you can choose one character?

Y0nnyy

---

**Comment by kegesch** [comment]
Habe you already checked Ctrl-Shift-Q? Is this what you mean?

**Comment by joaoghummel** [comment]
Oh sorry, yeah...

Just swapped the keys.
Hm, I have seen that there are more special chars missing, and i saw that you are ordering that as well.
I will take some notes while I use it, it would be easier for you to get the code in JS, or you would like to know only the chars that are missing?

**Comment by kegesch** [comment]
It would be easier if you code it and then i'll pull the request.

**Comment by joaoghummel** [comment]
Hi, I am back,
Hm, about that Shortcut, i discovered why it doesn't worked before.
I was using Mac, Ctrl-Shift-Q close the program.

**Comment by kegesch** [comment]
Hi, oh uhm that's not good... i thought cmd+q closes the programm? I have no mac so i'm afraid i can't test it on it. But i could change the command, some suggestions to which one i should change?

**Comment by joaoghummel** [comment]
Hmm, I use it at work, cant check the best shortcut right now.

Its just change the key binding at the final of the code right?

I got emmet extesion too and it take a lot of shorcut, gonna try to find something that dont conflict.

But there is something pretty bad too, windows shorcuts aren't even close to mac shortcuts.

I will check if there is some shortcut library to help on it

--- Mensagem Original ---

De: "Jonas Geschke" notifications@github.com
Enviado: 26 de novembro de 2014 18:23
Para: "Y0nnyy/SpecialChars" SpecialChars@noreply.github.com
Cc: "JoaoGHummel" joaoghummel@outlook.com
Assunto: Re: [SpecialChars] Enchacement (#15)

Hi, oh uhm that's not good... i thought cmd+q closes the programm? I have no mac so i'm afraid i can't test it on it. But i could change the command, some suggestions to which one i should change?

---

**Comment by kegesch** [comment]
yes it is. There is an online page in brackets' Website wäre you can look at but then there is still the Problem with mac.

**Comment by joaoghummel** [comment]
Hi,
Ctrl-Shift-N seems to work at both, at least, there is nothing mentioned over here:
[Brackets Shhortcuts](https://github.com/adobe/brackets/wiki/Brackets-Shortcuts)

See ya, gonna update those chars soon.

> P.S/TIP: update readme.md or you can wait all new adds

**Comment by kegesch** [comment]
okay, so do you change the command or should i? What do you mean in your P.S.?

**Comment by joaoghummel** [comment]
First time doing a pull request, i guess that i made it right.

The P.S:
I will be adding some chars in it and, so you would need to change the read.me file, that has the description about how to use Special Chars.

But i guess that i can make a pull request with those file too right?

**Comment by kegesch** [comment]
alright, yes you could do this, too.

JoaoGHummel notifications@github.com schrieb am Fr., 28. Nov. 2014 21:03:
