### ISSUE TITLE
HTML only

### ISSUE THREAD

**Issue by thany** [kegesch/SpecialChars#17]
This plugins seems to be doing its work not only in HTML, but in every kind of file.

Inserting `&ouml;` in javascript in not very useful, unless we happen to be writing a HTML-string (even then, using straight characters is fine, escaped or not). If anything, it's more useful to convert it to an escape sequence (ö -> `\xf6` or `\u00f6`) but only when inside a string. Same goes for CSS, but then the escape sequence looks slightly different (ö -> `\f6␠`, including the space).

**Comment by kegesch** [comment]
I will probably fix this in 3-4 weeks ... for now you can uncheck this plugin in the edit menu and it won't convert automatically.

**Comment by kegesch** [comment]
now it's only working in html-files
