### ISSUE TITLE
Conflict with "Brackets Themes Webpage" shortcut

### ISSUE THREAD

**Issue by santiagofn** [kegesch/SpecialChars#9]
There is a conflict between "Brackets Themes Webpage"'s shortcut and this extension's shorcut. It makes impossible to use the sorcut to transform an special character to its HTML entity.

**Workaround**: install the extension "Brackets Key Remapper", delete "Brackets Themes" shortcut and then reinstall "SpecialChars".

**Comment by kegesch** [comment]
what do you mean with Brackets Themes Webpage's shortcut? Is it another extension or has something to do with the ne themes in brackets, because i can't find it. Do you have another suggestion for a new Shortcut?

**Comment by santiagofn** [comment]
I think it's an option that came with the new 'Theme' functionality:

![brackets - theme web 2](https://cloud.githubusercontent.com/assets/8375708/3896092/517b24d0-2254-11e4-94bb-61b2589c92f5.png)

(1. The screenshot looks strange because I use Brackets on Ubuntu. 2. The shorcut is not visible because I delete it using another extension).

I checked it by uninstalling extensions, and it doesn't seem to have any relation with the ones I've installed.

About any suggestion for a new shorcut, I just see TextMate uses "Ctrl+Shift+7", a Notepad++ plugin uses "Ctrl+E"... I suppose you could use something like "Ctrl+Shift+E".

**Comment by kegesch** [comment]
![brackets](https://cloud.githubusercontent.com/assets/7421630/3910077/97275e20-2314-11e4-81c5-ddbaa4def804.png)

As you can see, although it's in german (I apologize for that), i haven't got this "Brackets Themes (WEB site) section. 

And so far the shortcuts Brackets' website are right ( https://github.com/adobe/brackets/wiki/Brackets-Shortcuts ) the shortcut should be free. "Ctrl+Shift+E" is occupied. I could use "Ctrl-Alt-E"?

**Comment by santiagofn** [comment]
@Y0nnyy, I owe you an apologize: a little further investigation made me realize the problematic shortcut was created by the extension [Tutorials](https://github.com/Denisov21/W3Schools).
I think you can close this issue, either changing the shortcut or leaving it this way, as it doesn't cause problems with the Bracket's core app.

**Comment by kegesch** [comment]
Okay, thank you for helping, though!
